import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import type { ReactElement } from "react";
import Navbar from "./Nav";

const Layout = ({ children }: { children: ReactElement }) => {
  const currentRoute = useRouter().pathname;

  return (
    <div /*className="bg-gradient-to-b from-[#2e026d] to-[#15162c]"*/>
      <Head>
        <link rel="icon" href="/favicon.ico" />
        <title>Jason Michael</title>
        <meta name="description" content="Generated by create-t3-app" />
        <meta name="theme-color" content="#27272a" />
        <meta property="og:site_name" content="Jason" />
        <meta
          property="og:title"
          content={`jason${
            currentRoute.slice(1).length > 1
              ? ` // ${currentRoute.slice(1)}`
              : ``
          }`}
        />
        <meta property="og:type" content="website" />
        <meta
          property="twitter:title"
          content={`jason${
            currentRoute.slice(1).length > 1
              ? ` // ${currentRoute.slice(1)}`
              : ``
          }`}
        />
      </Head>
      <Navbar path={currentRoute} />
      {children}
    </div>
  );
};

export default Layout;
