import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import type { ReactElement } from "react";
import Navbar from "./Nav";
import { KBarProvider } from "kbar";
import { actions } from "../lib/actions";
import Palette from "./Cmd";
import MobileNav from "./MobileNav";
import FloatingButton from "./FloatingButton";

const Layout = ({ children }: { children: ReactElement }) => {
  const currentRoute = useRouter().pathname;

  return (
    <div>
      <Head>
        <link rel="icon" href="/favicon.ico" />
        <title>Jason Michael</title>
        <meta name="description" content="Generated by create-t3-app" />
        <meta name="theme-color" content="#27272a" />
        <meta property="og:site_name" content="Jason Michael" />
        <meta
          property="og:title"
          content={`jason${
            currentRoute.slice(1).length > 1
              ? ` // ${currentRoute.slice(1)}`
              : ``
          }`}
        />
        <meta property="og:type" content="website" />
        <meta
          property="twitter:title"
          content={`jason${
            currentRoute.slice(1).length > 1
              ? ` // ${currentRoute.slice(1)}`
              : ``
          }`}
        />
      </Head>
      <KBarProvider actions={actions}>
        <main className="font-clash max-h-auto relative flex min-h-screen flex-col items-center bg-zinc-100 overflow-x-hidden selection:bg-zinc-200/30 dark:bg-zinc-900">
          <Palette />
          <div className="flex h-full w-full">
            <div className="hidden w-full md:block lg:block">
              <Navbar path={currentRoute} />
            </div>
            <div className="fixed top-0 z-50 block w-full px-8 pt-4 md:hidden lg:hidden">
              <MobileNav path={currentRoute} />
            </div>
          </div>
          {children}
        </main>
      </KBarProvider>
      {/* <FloatingButton /> */}
    </div>
  );
};

export default Layout;
